---
title: "De1ctf2019-Re_Sign" 
date: 2019-08-06
categories: CTF
tags : UPX custom-table-base64
---
```
De1ctf의 re_sign 이라는 문제였고 문제 설명에는 UPX라고 적혀있었다.
```

```
올리 디버거로 MUP 방식으로 덤프를 뜨고 ida로 동적디버깅 해보려고했는데 kernel32.dll 오류때문에 할수없어서 ida는 정적으로 immunity 디버거를 동적으로 사용하면서 분석했다.
```



![len](https://raw.githubusercontent.com/slyfizz3/slyfizz3.github.io/master/image/Re_Sign/len.png)

분석을 해보니 custom table base64 encrypt를 한 플래그의 길이가 48글자 인지 체크하고

![check](https://raw.githubusercontent.com/slyfizz3/slyfizz3.github.io/master/image/Re_Sign/check.png)

테이블을 체크하고

![checkdone](https://raw.githubusercontent.com/slyfizz3/slyfizz3.github.io/master/image/Re_Sign/checkdone.png)

위의 체크가 모두 맞는지를 카운트한다.

![fail](https://raw.githubusercontent.com/slyfizz3/slyfizz3.github.io/master/image/Re_Sign/fail.png)

플래그가 맞으면 success를 아니라면 fail을 출력한다.

즉 테이블만 알면 복호화할수 있는데

![table](https://raw.githubusercontent.com/slyfizz3/slyfizz3.github.io/master/image/Re_Sign/table.png)

이 과정에서 이 테이블과 

```
"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/="
```
이 테이블을 이용한다.

```python
import string,base64
table="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/="
	
m=[0x08,0x3B,0x01,0x20,0x07,0x34,0x09,0x1F,0x18,0x24,0x13,0x03,0x10,0x38,0x09,0x1B,0x08,0x34,0x13,0x02,0x08,0x22,0x12,0x03,  0x05,0x06,0x12,0x03,0x0F,0x22,0x12,0x17,0x08,0x01,0x29,0x22,0x06,0x24,0x32,0x24,0x0F,0x1F,0x2B,0x24,0x03,0x15,0x41,0x41]
enc=''
for i in range(len(m)):
	enc+=table[m[i]-1]
enc="H6AfGzIeXjSCP3IaHzSBHhRCEFRCOhRWHAohFjkjOeqjCU=="
table=base64.b64encode(table)
arr="UA93I4S6IjB9OqpEPAcYA55OAkISSwZGDSyBGeRqHDHrJ6wuJlfpKemdLF9hZ7SlZzBcXM0fEMEjRPGzT3qiWhj="
tb=string.maketrans(arr,table)
rb=enc.translate(tb)
print(base64.b64decode(rb))
```
알아낸 정보들로 올바른 테이블을 만들어 주고 복호화하면 

```
de1ctf{EBL4Zguag3B1sBK3KeJ3_MtJi4	
```

중간에 몇몇 문자열이 base64collision이 일어나서 플래그가 이상하게 나오는데 이부분을 직접 디버깅하면서 수정했다.

```
FLAG:de1ctf{E_L4nguag3_1s_K3KeK3_N4Ji4}
```

![success](https://raw.githubusercontent.com/slyfizz3/slyfizz3.github.io/master/image/Re_Sign/success.png)

Success!!

xctf 관련 문제는 항상 한문제도 못풀었는데 이번에는 풀어서 다행이다.
